version: '2'
services:
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=kong
      - CASSANDRA_PASSWORD=kong
      - CASSANDRA_PASSWORD_SEEDER=yes
  kong:
    image: docker.io/bitnami/kong:2-debian-10
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      - KONG_MIGRATE=yes
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_CASSANDRA_PASSWORD=kong
      - KONG_ADMIN_LISTEN_ADDRESS=0.0.0.0
volumes:
  cassandra_data:
    driver: local